const TEAM_NAMES_ES: Record<string, string> = {
  Mexico: "México",
  "United States": "Estados Unidos",
  "South Korea": "Corea del Sur",
  "Czech Republic": "República Checa",
  "Bosnia and Herzegovina": "Bosnia",
  "South Africa": "Sudáfrica",
  "Ivory Coast": "Costa de Marfil",
  "Democratic Republic of the Congo": "RD Congo",
  "Saudi Arabia": "Arabia Saudita",
  "New Zealand": "Nueva Zelanda",
  Japan: "Japón",
  Brazil: "Brasil",
  Germany: "Alemania",
  Spain: "España",
  France: "Francia",
  England: "Inglaterra",
  Portugal: "Portugal",
  Netherlands: "Países Bajos",
  Argentina: "Argentina",
  Colombia: "Colombia",
  Uruguay: "Uruguay",
  Ecuador: "Ecuador",
  Panama: "Panamá",
  Canada: "Canadá",
  Australia: "Australia",
  Morocco: "Marruecos",
  Switzerland: "Suiza",
  Belgium: "Bélgica",
  Croatia: "Croacia",
  Scotland: "Escocia",
  Turkey: "Turquía",
  Iran: "Irán",
  Iraq: "Irak",
  Algeria: "Argelia",
  Tunisia: "Túnez",
  Egypt: "Egipto",
  Ghana: "Ghana",
  Senegal: "Senegal",
  Norway: "Noruega",
  Sweden: "Suecia",
  Austria: "Austria",
  Jordan: "Jordania",
  Uzbekistan: "Uzbekistán",
  "Cape Verde": "Cabo Verde",
  Haiti: "Haití",
  Paraguay: "Paraguay",
  Qatar: "Catar",
  "Curaçao": "Curazao",
};

export function toSpanishTeamName(name: string): string {
  return TEAM_NAMES_ES[name] ?? name;
}
